export default {
  "login": "vodnalasricharan",
  "id": 50229017,
  "node_id": "MDQ6VXNlcjUwMjI5MDE3",
  "avatar_url": "https://avatars.githubusercontent.com/u/50229017?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/vodnalasricharan",
  "html_url": "https://github.com/vodnalasricharan",
  "followers_url": "https://api.github.com/users/vodnalasricharan/followers",
  "following_url": "https://api.github.com/users/vodnalasricharan/following{/other_user}",
  "gists_url": "https://api.github.com/users/vodnalasricharan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/vodnalasricharan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/vodnalasricharan/subscriptions",
  "organizations_url": "https://api.github.com/users/vodnalasricharan/orgs",
  "repos_url": "https://api.github.com/users/vodnalasricharan/repos",
  "events_url": "https://api.github.com/users/vodnalasricharan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/vodnalasricharan/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sricharan",
  "company": "IBM CIO",
  "blog": "vodnalasricharan.github.io",
  "location": "Bangalore,KA,INDIA",
  "email": null,
  "hireable": true,
  "bio": "Software Developer working on React and Business automation tool. ",
  "twitter_username": "itsmesricharan",
  "public_repos": 26,
  "public_gists": 0,
  "followers": 16,
  "following": 6,
  "created_at": "2019-05-03T06:55:49Z",
  "updated_at": "2022-11-29T10:41:09Z"
};
